
`sgutils` is a collection of highlevel independant submodules, to work on some developed products. 

Path
====

[path](https://github.com/SylvainGuieu/path/) Provide a way to define directory or file path in an object oriented way

Smartplotlib
============

[smartplotlib](https://github.com/SylvainGuieu/smartplotlib/) Is a usefull wraper around the matplotlib library allowing to detach more clearly the ploting to the data and to change plot render easely

Quantity
============

[quantity](https://github.com/SylvainGuieu/quantity/) redefine numerocal values (float, array, etc) so they can be attached to a physical quantity with a unit.


