# Modules
`sgutils` is a collection of highlevel independant submodules, to work on some developed products. 
## path

[path](https://github.com/SylvainGuieu/path/) Provide a way to define directory or file path in an object oriented way

